#variable "vm_name" {}
#variable "vm_pool_name" {}
#variable "vm_network_id" {}
#variable "vm_size" {}
#variable "vm_memory" {}
#variable "vm_vcpu" {}
#variable "vm_hostname" {}
#variable "vm_mac" {}
#variable "vm_ip" {}
