- name: Generate config files for terraform,ansible
  hosts: localhost
  gather_facts: no

  vars:
    ssh_public_key_content: "{{ lookup('file', ssh_public_key_path ) }}"

  pre_tasks:
   - name: Delete tmp pull-secret
     file: 
        path: "/tmp/{{item}}"
        state: absent
     with_items:
     - "{{pull_secret_path|basename}}"
     - "pull-secret"
     become: true

   - name: Create bin folder
     file: 
        path: "../bin"
        state: directory
      
  tasks:
   - name: Create terraform.tfvar file for prep
     template:
       src: ../templates/terraform.tfvars.j2
       dest: ../../terraform.tfvars 
       backup: yes 
       force: yes

   - name: Create connection.tf 
     template: 
       src: ../templates/connection.tf.j2
       dest: "{{ item }}"
       backup: yes
       force: yes
     with_items:
      - "../../connection.tf"
      - "../../../ocp4/connection.tf"
   
   - name: Copy pull secert 
     shell: "cp {{pull_secret_path}} /tmp/."
    
   - name: Update pull-secret
     shell: "{{ item }}"
     with_items:
     - "podman login --authfile /tmp/{{pull_secret_path|basename}}  -u {{quay_id}}   -p {{quay_pw}} {{quay_local_registry}} --tls-verify=false"
     - "jq -c  '.' /tmp/{{pull_secret_path|basename}} > {{pull_secret_json_path}}"
     when: disconnected is defined
     become: false

   - name: Convert pull-secret text to json
     shell: "cp {{pull_secret_path}}  {{pull_secret_json_path}}"
     when: disconnected is not defined
   
   - set_fact:
      pull_secret_json_content: "'{{ lookup('file', pull_secret_json_path ) }}'"

   - name: Generate inventory file
     template:
       src: ../templates/inventory.j2
       dest: ../inventory
       backup: yes
       force: yes
     become: false
 
   - name: Generate Libvirt network xlst file for bootp(iPXE)
     template:
       src: ../templates/bootp.xsl.j2
       dest: ../../bootp.xsl
       backup: yes
       force: yes
 

